# Generated by Django 5.1.2 on 2024-11-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_alter_bb_price_alter_bb_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='new_file',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]

